baseurl = "/"
languageCode = "en-us"
title = "Eric's COVID tracker"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "FAQ"
    identifier = "faq"
    pre = "fa fa-question-circle"
    url = "/faq/"
    weight = 1

[[menu.main]]
    name = "GitHub"
    identifier = "github"
    pre = "fab fa-github"
    url = "https://github.com/ericedwardbryant/covid"
    weight = 2


[params]
    owner = "Eric Bryant, PhD"
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "landscape.png"
    width = 50
    height = 50
    alt = "Logo"

