---
title: Homepage
author: Eric Bryant, PhD
include-before: >
  First time here? Check out the [FAQ](/faq/)! Otherwise, jump to:
output:
  blogdown::html_page:
    toc: yes
---



```{r include = FALSE}
# Load R packages, functions, and settings
source(here::here("requirements.R"))

# Where to save new cases in CA
csv_cases <- here("data/new-cases-ca-v2.csv")
csv_hsp   <- here("data/hospitalization-ca-v2.csv")

# ---- !!! Population data now provided from CA directly as of 2021-03-13 ----
# Population from: https://worldpopulationreview.com/us-counties/ca/los-angeles-county-population
#la_population <- 10079000

# Population from: https://worldpopulationreview.com/us-counties/ca/santa-clara-county-population
#sc_population <- 1945940
# ---- !!! -------------------------------------------------------------------

# Range of dates
#dates <- lubridate::today("UTC") + c(-255, 110)
#dates <- lubridate::today("UTC") + c(-500, 150)
dates <- c(as.Date("2020-11-01"), lubridate::today("UTC") + 150)

# Download data from https://data.ca.gov
# Only downloads once a day unless force = TRUE
download_new_cases_ca_csv_v2(csv_cases)
download_hospitalization_ca_csv_v2(csv_hsp)
```

**UPDATE 2021-12-17:** O.M.I.C.R.O.N REVIVAL. Katrina, do. not. panic... yet!

Los Angeles
--------------------------------------------------------------------------------

For the most recent information, I recommend reading the
[LA county public health press releases](http://publichealth.lacounty.gov/media/coronavirus/#news).

```{r covid-los-angeles, fig.height = 7}
county <- "Los Angeles"

la_population <-
  read_csv(csv_cases, col_types = cols()) %>%
  filter(county == {{ county }}) %>%
  pull(population) %>%
  median() # compromise since second scale needs to be a linear transformation

figure_new_cases(csv_cases, county, population = la_population, date_limits = dates) /
  figure_new_cases_change(csv_cases, county, date_limits = dates) /
  figure_hospitalization(csv_hsp, county, date_limits = dates)
```


Adding numbers for last 30 days since there are lots of reporting dips and
spikes, so it can be usefull to crossreference with recent numbers.

```{r covid-los-angeles-table-01}
df_cases <-
  read_csv(csv_cases, col_types = cols()) %>%
  filter(.data$county == .env$county) %>%
  # Calculate estimates
  arrange(date) %>%
  mutate(
    count_new_roll  = slide_dbl(count_new, median, .before = 7L, .after = 7L),
    count_new_loess = predict_loess(date, count_new, span = 0.11),
    count_new_loess_diff = count_new_loess - lag(count_new_loess),
    count_new_loess_fc   = count_new_loess / lag(count_new_loess),
    count_new_loess_diff_weekly = count_new_loess - lag(count_new_loess, 7L),
    count_new_loess_fc_weekly = count_new_loess / lag(count_new_loess, 7L)
  ) %>%
  select(
    Date = date,
    "New cases" = count_new,
    "Smooth estimate" = count_new_loess,
    "2 week median" = count_new_roll,
    "Daily change" = count_new_loess_diff,
    "Weekly change" = count_new_loess_diff_weekly,
    "Daily fold change" = count_new_loess_fc,
    "Weekly fold change" = count_new_loess_fc_weekly
  )

df_hsp <-
  read_csv(csv_hsp, col_types = cols()) %>%
  # Date hard censored due to change in reporting criteria
  filter(.data$county == .env$county, date >= as.Date("2020-05-01")) %>%
  # Combine confirmed and suspected counts (at this point most are confirmed)
  # In the spring there were more "suspected" probably due to testing backlogs?
  mutate(
    hsp = hsp_covid_confirmed + hsp_covid_suspected,
    icu = icu_covid_confirmed + icu_covid_suspected,
    hsp = hsp - icu # remove ICU cases from inpatient (the figure will stack)
  ) %>%
  select(Date = date, "Hospitalized" = hsp, "ICU" = icu, "Open ICU beds" = icu_available_beds)

df_data <- left_join(df_hsp, df_cases, by = "Date")

df_data %>%
  top_n(30, Date) %>%
  arrange(desc(Date)) %>%
  #mutate(across(where(is_double) & !Date, ~as.integer(round(.)))) %>%
  gt::gt() %>%
  gt::fmt_number(columns = c(`Smooth estimate`, `2 week median`, `Daily change`, `Weekly change`), decimal = 0) %>%
  gt::fmt_number(columns = ends_with("fold change"), decimal = 2) %>%
  gt::cols_width(
    Date ~ px(100),
    ICU  ~ px(80)
  ) %>%
  gt::gtsave(paste0(tempfile(), ".png"))
```


I was curious to compare prior lags in hospitalizations from cases to see where
we would be if Omicron is behaving similarly to the previous Delta wave (post
vaccination effort, and return to normal), and the bigger winter 2021 wave (pre
vaccination effort, lockdown). The data below are normalized between 1 and 0 for
comparison purposes. Hospitalization and ICU data have been shifted back 7 days
which corresponds roughly to the lag seen in the rise of hospitalizations for
the big winter 2021 wave. I am seeing a rise in hospitalizations for Omicron,
but it appears to be considerably delayed relative to previous waves. There is
no evidence yet of a similarly large increase in ICU admission as was typically
seen in the prior waves. As of this note on Thursday, December 30th, I think
we are still a couple of weeks out from knowing the trajectory of the LA Omicron
ICU and hospitalization wave.

```{r covid-los-angeles-figure-02, fig.height = 2.5}
x <-
  df_data %>%
  filter(Date > as.Date("2020-09-01")) %>%
  mutate(
    norm_cases = (`Smooth estimate` - min(`Smooth estimate`)) / max(`Smooth estimate` - min(`Smooth estimate`)),
    norm_hsp   = (Hospitalized - min(`Hospitalized`)) / max(Hospitalized - min(Hospitalized)),
    norm_icu   = (ICU - min(ICU)) / max(ICU - min(ICU)),
    lag_adjusted_hsp = lead(norm_hsp, 7),
    lag_adjusted_icu = lead(norm_icu, 7)
  )

x %>%
  select(
    Date,
    Cases = norm_cases,
    `Lag adjusted hospitalizations` = lag_adjusted_hsp,
    `Lag adjusted ICU` = lag_adjusted_icu
  ) %>%
  pivot_longer(cols = -Date, names_to = "group", values_to = "Normalized counts") %>%
  filter(complete.cases(.)) %>%
  ggplot(aes(x = Date, y = `Normalized counts`, color = group)) +
  scale_color_manual(values = c("blue", "maroon2", "olivedrab")) +
  scale_x_date(
    date_breaks = "4 month",
    date_labels = "%b",
    date_minor_breaks = "1 month",
    sec.axis =
      dup_axis(
        breaks = scales::date_breaks("1 year"),
        labels = scales::date_format("%Y")
      )
  ) +
  geom_vline(xintercept = as.Date(c("2021-01-01", "2022-01-01", "2023-01-01"), tz = ""), linetype = "dotted") +
  geom_line() +
  labs(
    title = str_c(county, " county"),
    y = "Normalized counts",
    caption =
      str_c(
        "<span style='color:blue'>Blue line</span>: New cases estimate",
        "<span style='color:olivedrab'>Green line</span>: ICU, 7 day lag adjusted",
        "<span style='color:maroon2'>Purple line</span>: Hospitalizations, 7 day lag adjusted",
        sep = "<br>"
      )
  ) +
  theme(
    legend.position = "none",
    plot.caption = ggtext::element_markdown(hjust = 0, size = 7),
    aspect.ratio = 0.5,
    axis.title.x = element_blank(),
    axis.text.x = element_text(hjust = 0)
  )

```

Santa Clara
--------------------------------------------------------------------------------

For the most recent information, I recommend reading the
[Santa Clara county public health press releases](https://www.sccgov.org/sites/covid19/Pages/archives.aspx).

```{r covid-santa-clara, fig.height = 7}
county <- "Santa Clara"

sc_population <-
  read_csv(csv_cases, col_types = cols()) %>%
  filter(county == {{ county }}) %>%
  pull(population) %>%
  median() # compromise since second scale needs to be a linear transformation

figure_new_cases(csv_cases, county, population = sc_population, date_limits = dates) /
  figure_new_cases_change(csv_cases, county, date_limits = dates) / 
  figure_hospitalization(csv_hsp, county, date_limits = dates)
```
